name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # - run: apt-get install -y tree
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          always-auth: false
          # cache: "yarn"
          # cache-dependency-path: "yarn.lock"
          # cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          # restore-keys: |
            # node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Yarn deps
        uses: actions/cache@v5
        with:
          path: 'node_modules'
          key: node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-
      - name: Install npm deps
        run: yarn
      - run: pwd
      - run: find . -maxdepth 2
      - run: find ~/ -maxdepth 2
      - name: Run Tests
        run: yarn test
