name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          always-auth: false
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          # cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          restore-keys: |
            node-cache-${{ runner.os }}-${{ runner.arch }}-${{ runner.tool_cache }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install npm deps
        run: yarn
      - name: Run Tests
        run: yarn test
