name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # - run: apt-get install -y tree
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          always-auth: false
          # cache: "yarn"
          # cache-dependency-path: "yarn.lock"
      # - name: Cache Yarn deps
      #   uses: actions/cache@v5
      #   with:
      #     path: '/home/runner/.cache'
      #     key: node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Extract branch name
        run: echo "${{ github.head_ref }}"

      - name: Install latest Corepack
        run: npm install -g corepack@latest

      - name: Install modern Yarn
        run: corepack prepare yarn@4.16.0 --activate

      - name: Show Yarn version
        run: yarn --version

      - name: Get path for Yarn Cache
        id: yarn-cache-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Load Yarn Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-
      - name: Install npm deps
        run: yarn
      - name: Run Tests
        run: yarn test
        working-directory: ./packages/frontend

      - name: JS > Save Yarn Cache
        # if: github.head_ref == 'main' || github.head_ref == 'other-dummy-branch'
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: node-cache-${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('yarn.lock') }}
